Webkul\UVDesk\CoreBundle\Entity\Ticket:
    type: entity
    table: uv_ticket
    repositoryClass: Webkul\UVDesk\CoreBundle\Repository\TicketRepository
    oneToMany:
        threads:
            targetEntity: Thread
            mappedBy: ticket
        ratings:
            targetEntity: TicketRating
            mappedBy: ticket
    manyToOne:
        status:
            targetEntity: TicketStatus
            joinColumn:
                name: status_id
                referencedColumnName: id
        priority:
            targetEntity: TicketPriority
            joinColumn:
                name: priority_id
                referencedColumnName: id
        type:
            targetEntity: TicketType
            joinColumn:
                name: type_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL
        customer:
            targetEntity: User
            joinColumn:
                name: customer_id
                referencedColumnName: id
                onDelete : cascade
        agent:
            targetEntity: User
            joinColumn:
                name: agent_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL
        supportGroup:
            targetEntity: SupportGroup
            inversedBy: tickets
            joinColumn:
                name: group_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL
        supportTeam:
            targetEntity: SupportTeam
            joinColumn:
                name: subGroup_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL
    manyToMany:
        supportTags:
            targetEntity: Tag
            joinTable:
                name: uv_tickets_tags
                joinColumns:
                    ticket_id:
                        referencedColumnName: id
                        onDelete: cascade
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
                        onDelete: cascade
        collaborators:
            targetEntity: User
            joinTable:
                name: uv_tickets_collaborators
                joinColumns:
                    ticket_id:
                        referencedColumnName: id
                        onDelete : cascade
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
                        onDelete : cascade               
        supportLabels:
            targetEntity: SupportLabel
            joinTable:
                name: uv_tickets_labels
                joinColumns:
                    ticket_id:
                        referencedColumnName: id
                        onDelete: cascade
                inverseJoinColumns:
                    label_id:
                        referencedColumnName: id
                        onDelete: cascade
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        source:
            type: string
            length: 191
        mailboxEmail:
            type: string
            length: 191
            nullable: true
        subject:
            type: text
        referenceIds:
            type: text
            nullable: true
        isNew:
            type: boolean
            options:
                default: true
        isReplied:
            type: boolean
            options:
                default: false
        isReplyEnabled:
            type: boolean
            options:
                default: true
        isStarred:
            type: boolean
            options:
                default: false
        isTrashed:
            type: boolean
            options:
                default: false
        isAgentViewed:
            type: boolean
            options:
                default: false
        isCustomerViewed:
            type: boolean
            options:
                default: false
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks: {  }
