# Member panel agent dashboard resources
uvdesk_core_member_authentication_routing_resources:
    resource: "@UVDeskCoreBundle/Resources/config/routes/auth.yaml"

# Member panel agent dashboard resources
uvdesk_core_member_panel_routing_resources:
    resource: "@UVDeskCoreBundle/Resources/config/routes/members.yaml"

# Member panel agent dashboard resources
uvdesk_core_member_ticket_routing_resources:
    resource: "@UVDeskCoreBundle/Resources/config/routes/tickets.yaml"

# Member panel customer dashboard resources
uvdesk_core_member_customer_routing_resources:
    resource: "@UVDeskCoreBundle/Resources/config/routes/customers.yaml"
