# This file is the entry point to configure the routes for your dependencies.
uvdesk_core_bundle_member_routing_resources:
    resource: "@UVDeskCoreBundle/Resources/config/members.yaml"
    prefix:   /{_locale}/%uvdesk_site_path.member_prefix%/
    requirements:
        _locale: %app_locales%
    defaults:
        _locale: %locale%

uvdesk_core_bundle_public_routing_resources:
    resource: "@UVDeskCoreBundle/Resources/config/public.yaml"
    prefix:   /
    requirements:
        _locale: %app_locales%
    defaults:
        _locale: %locale%
